# 运行时异常恐慌

> 原文：<https://golangbyexample.com/runtime-error-panic-golang/>

# **概述**

程序中的运行时错误可能在以下情况下发生。以下所有情况也会造成**恐慌**

*   越界数组访问

*   在零指针上调用函数

*   在封闭信道上发送

*   不正确的类型断言

# **例**

让我们看一个由越界数组访问引起的运行时错误的例子。

```go
package main

import "fmt"

func main() {

	a := []string{"a", "b"}
	print(a, 2)
}

func print(a []string, index int) {
	fmt.Println(a[index])
}
```

**输出**

```go
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.checkAndPrint(...)
        main.go:12
main.main()
        /main.go:8 +0x1b
exit status 2
```

在上面的程序中，我们有一个长度为 2 的切片，我们试图在**打印**功能中访问索引为 2 的切片。不允许越界访问，从输出中可以看出，这将造成恐慌。请注意，在输出中有两件事

*   错误消息

*   恐慌发生的栈跟踪

在很多情况下，程序中可能会发生运行时错误。我们不会提到所有这些，但你会明白的