# Go (Golang)中的紧急堆栈跟踪

> 原文:[https://golangbyexample.com/panic-stack-trace-go/](https://golangbyexample.com/panic-stack-trace-go/)

# **概述**

**golang 的 debug** 包提供了 **StackTrace** 功能，可以用来打印恢复功能中死机的堆栈痕迹

# **例**

让我们来看一个节目

```
package main
import (
    "fmt"
    "runtime/debug"
)
func main() {
    a := []string{"a", "b"}
    checkAndPrint(a, 2)
    fmt.Println("Exiting normally")
}
func checkAndPrint(a []string, index int) {
    defer handleOutOfBounds()
    if index > (len(a) - 1) {
        panic("Out of bound access for slice")
    }
    fmt.Println(a[index])
}
func handleOutOfBounds() {
    if r := recover(); r != nil {
        fmt.Println("Recovering from panic:", r)
        fmt.Println("Stack Trace:")
        debug.PrintStack()
    }
}
```

**输出**

```
Recovering from panic: Out of bound access for slice
Stack Trace:
goroutine 1 [running]:
runtime/debug.Stack(0xd, 0x0, 0x0)
        stack.go:24 +0x9d
runtime/debug.PrintStack()
        stack.go:16 +0x22
main.handleOutOfBounds()
        main.go:27 +0x10f
panic(0x10ab8c0, 0x10e8f60)
        /Users/slohia/Documents/goversion/go1.14.1/src/runtime/panic.go:967 +0x166
main.checkAndPrint(0xc000104f58, 0x2, 0x2, 0x2)
        main.go:18 +0x111
main.main()
        main.go:11 +0x81
Exiting normally
```

在上面的程序中，我们有一个函数 **checkAndPrint** ，它在参数中传递的索引处检查并打印切片元素。如果传递的索引大于数组的长度，程序就会死机。我们还在函数**的开始处添加了一个名为 **handleOutIfBounds** 的延迟函数**。该函数包含如下的恢复函数调用

```
if r := recover(); r != nil {
    fmt.Println("Recovering from panic:", r)
}
```

**恢复**功能会捕捉到恐慌，我们也可以打印恐慌的消息。

```
Recovering from panic: Out of bound access for slice
```

我们使用 **StackTrace** 函数在恢复函数中打印死机的堆栈跟踪。从输出中可以看出，它打印了正确的堆栈跟踪